apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db-service
    app: demo-test-app
spec:
 ports:
 - port: 5432
   targetPort: 5432
 selector:
   name: postgress-pod
   app: demo-test-app
