apiVersion: v1
kind: Pod
metadata:
  name: postgress-pod
  labels:
    name: postgress-pod
    app: demo-test-app
spec:
  containers:
    - name: postgress-app
      image: postgres:9.4
      ports:
        - containerPort: 5432
